name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  Build-and-Release:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: prepare
        run: |
          mkdir go
          echo "GOPATH=${HOME}/go" >> $GITHUB_ENV
          echo "PATH=${PATH}:${GOPATH}/bin" >> $GITHUB_ENV
          GO111MODULE=on go get github.com/lucor/fyne-cross/v2/cmd/fyne-cross
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: build
        run: |
          ${GOPATH}/bin/fyne-cross windows -arch=386,amd64
          # ${GOPATH}/bin/fyne-cross linux -arch=386,amd64
          # others
          mkdir build
          cp fyne-cross/dist/windows-amd64/timer.exe.zip build/timer.windows.amd64.exe.zip
          cp fyne-cross/dist/windows-386/timer.exe.zip build/timer.windows.386.exe.zip


      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/timer.windows.386.exe.zip
            build/timer.windows.amd64.exe.zip
            # build/timer.linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}